# Should blocks be damaged? (Block Breaking)
block-damage: true

# When the explosion happens should the blocks be given to a player in range?
auto-pickup-exploded: false

# Should blocks regenerate?
# (Block Damage must be set to true)
block-regeneration: true

# Should effects be displayed when blocks are being regenerated?
block-regeneration-effects: true

# Should block physics be activated? 
block-physics: true

# Should falling block form on the ground?
block-form: false

# Should exploded blocks drop items?
block-drops: false

# When containers such as chests, furnaces, or hoppers are exploded shall they drop their contents like normal?
# (Note: If container drops is enabled container saving and restoring will be automatically disabled due to incompatibility via code)
container-drops: false

# Should block physics have particles? 
block-physics-particles: true

# These are the physics offsets for each block in motion.
# (Fun to play with enjoy!)
physics-offset-x: 1
physics-offset-y: 2
physics-offset-z: 2

# How many ticks should be calculated before the block regeneration takes place? (In Ticks)
# (20 Ticks = 1 Second)
regeneration-delay-ticks: 60

# The lower this value is(even negative), the faster the regeneration of the blocks will be!
regeneration-speed: 0

# Add the worlds you want regeneration to take effect in.
regeneration-worlds: ["world"]

# Upon regeneration should any block that has a inventory have it's contents restored?
save-container-contents: true

# Upon regeneration should any sign have it's text restored?
save-sign-information: true

# When TNT is blown up should it become Primed TNT?
convert-tnt: true

# What should the fuse be on the TNT?
convert-tnt-fuse: 20

# Should PhysicsToGo hook into WorldGuard?
use-worldguard: false

# Should the event be cancelled when in a WorldGuard region that doesn't allow explosions?
cancel-event: true

# Add the regions to this list that you don't want PhysicsToGo to work in.
blocked-worldguard-regions: ["blocked_region"]

# If this list has a region in it PhysicsToGo will ONLY work in that region period. (This ignores "blocked-worldguard-regions" and everything)
only-worldguard-regions: []

# Add blocks that you do not want physics to take effect on.
# Latest Material List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
block-physic-blacklist: ["MOB_SPAWNER"]

# Add blocks that you do not want regeneration to take effect on.
# Latest Material List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
block-regeneration-blacklist: ["MOB_SPAWNER"]

# Having this enable will make PhysicsToGo only work in specific worlds.
per-world-support: false
# Add the worlds you want PhysicsToGo to work in below.
worlds: ["world", "world_the_nether"]

