name: PhysicsToGo
version: 1.6.5
main: XZot1K.plugins.ptg.PhysicsToGo
author: XZot1K
description: Listeners newer, re-done version of XZot1K's physics portion of his plugin Explode!
softdepend: [WorldGuard, WorldEdit, Factions, MassiveCore]
commands:
   ptg:
     default: op